
# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# See http://travis-ci.org/ for details

# This file is heavily inspired by Peter Cock's efforts. See more details at
# http://blastedbio.blogspot.com/2013/09/using-travis-ci-for-testing-galaxy-tools.html

# We need Python 2.6 or 2.7 to run Galaxy but many Galaxy tools also need Java
# to run the simplest way to get that installed is to just start with "java".
# (which will still have a system python installed).
language: python
cache: pip
dist: xenial

python: 2.7

jobs:
  include:
    - stage: lint
      script: planemo l
    - stage: test
      script: planemo test --install_galaxy --no_cache_galaxy
    - stage: deploy
      script: planemo shed_update --shed_key_from_env SHED_KEY -t toolshed

install:
  - pip install planemo
  - planemo conda_init
  - planemo conda_install .
